name: Publish_App

on:
  workflow_dispatch:
  push:
    tags: ['v*']
    branches: [ main ]
    paths:
      - 'src/SignalPlot/**'

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Test
      run: dotnet test .\src\SignalPlot\


    - name: Publish
      run: |
        dotnet publish -c Release .\src\SignalPlot\SampleApp\SampleApp.Wasm -o out\Wasm
        dotnet publish -c Release -r win10-x64 -p:PublishSingleFile=true -p:Platform="x64" --self-contained .\src\SignalPlot\SampleApp\SampleApp.Windows\ -o out\WinUI
    
    - name: Upload Wasm artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SampleApp.Wasm
        path: out\Wasm\

    - name: Upload WinUI artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SampleApp.WinUI
        path: out\WinUI\
        

